# Generated by Django 3.1.5 on 2021-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20210106_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='pulistan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avd', models.CharField(default='', max_length=6)),
                ('beskrivning', models.CharField(default='', max_length=20)),
                ('artal', models.TextField(default='', max_length=20)),
                ('kostnad', models.TextField(default='', max_length=20)),
                ('projektnr', models.TextField(default='', max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
