# Generated by Django 3.1.5 on 2021-08-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_auto_20210819_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulistan',
            name='askande_fil',
            field=models.FileField(blank=True, null=True, upload_to='test1/resources/'),
        ),
    ]
