# Generated by Django 3.1.5 on 2021-08-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_pulistan_askande_fil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulistan',
            name='ansvar',
            field=models.TextField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='b_start',
            field=models.TextField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='konsekvens',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='motivering',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='motpart',
            field=models.TextField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='omfattning',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='projektansvarig',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='projektledare',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='rs',
            field=models.TextField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='pulistan',
            name='projektnr',
            field=models.TextField(default='', max_length=20),
        ),
    ]
