# Generated by Django 3.1.5 on 2021-08-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_auto_20210824_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulistan',
            name='b_klart',
            field=models.TextField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='pulistan',
            name='beviljan_m',
            field=models.TextField(default='', max_length=7),
        ),
    ]
