# Generated by Django 3.1.5 on 2021-01-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namnlista',
            name='hobby',
            field=models.TextField(default='', max_length=20),
        ),
    ]
