# Generated by Django 3.1.5 on 2021-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_namnlista_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namnlista',
            old_name='hobby',
            new_name='avd',
        ),
        migrations.RemoveField(
            model_name='namnlista',
            name='your_name',
        ),
        migrations.AddField(
            model_name='namnlista',
            name='avstallt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='namnlista',
            name='direktiv',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='namnlista',
            name='objektid',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='namnlista',
            name='operator',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='namnlista',
            name='utforare',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='namnlista',
            name='utfort',
            field=models.BooleanField(default=False),
        ),
    ]
