# Generated by Django 3.1.5 on 2021-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20210109_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='namnlista',
            name='ao',
            field=models.CharField(default='', max_length=6),
        ),
    ]
