# Generated by Django 3.1.5 on 2021-01-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_namnlista_ao'),
    ]

    operations = [
        migrations.AddField(
            model_name='namnlista',
            name='avstallt_datum',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='namnlista',
            name='utforare',
            field=models.TextField(default='', max_length=20),
        ),
    ]
