# Generated by Django 3.1.5 on 2021-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_auto_20210110_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='namnlista',
            name='las_lista',
            field=models.CharField(default='', max_length=20),
        ),
    ]
