# Generated by Django 3.1.5 on 2021-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_namnlista_las_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='namnlista',
            name='asvlutad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='namnlista',
            name='startad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='namnlista',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
